name: third
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Stolzl
      fonts:
        - asset: assets/fonts/Stolzl-Regular.ttf
    - family: TT
      fonts:
        - asset: assets/fonts/TTInterfaces-Regular.ttf
